### ISSUE TITLE
Errors in using, likely user error

### ISSUE THREAD

**Issue by justbest23** [MrMarble/zmk-viewer#18]
Heyo. I'm sure this is my fault, but I'm getting the following errors when I try to generate the image.

```
PS C:\Users\Troggo\Downloads\zmk-viewer-1.5.0-windows-amd64\zmk-viewer-1.5.0-windows-amd64> .\zmk-viewer generate -f C:\Users\Troggo\Downloads\slicemk-20231030-091248\slicemk-20231030-091248\slicemk_ergodox.keymap ergodox_ez/base
zmk-viewer 1.5.0
2023-10-30T11:39:42+02:00 INF Fetching keyboard layout.
2023-10-30T11:39:42+02:00 INF Parsing keymap file.
panic: runtime error: index out of range [77] with length 77

goroutine 1 [running]:
github.com/mrmarble/zmk-viewer/internal/img.drawKeymap(0xc000128160, {{0xc0007e0400, 0xc0001880c0, 0x0}}, 0xc000192300, 0x0, 0xffffffffffffffff)
        github.com/mrmarble/zmk-viewer/internal/img/generate.go:237 +0x305
github.com/mrmarble/zmk-viewer/internal/img.(*Image).GenerateLayouts(0xc000186ab0)
        github.com/mrmarble/zmk-viewer/internal/img/generate.go:83 +0x2b4
github.com/mrmarble/zmk-viewer/cmd/zmk-viewer/generate.generate({0xc0002e8840, 0xf}, {0x0, 0x1}, {0xc0000922a0, 0x57}, {0xc000092240, 0x60}, 0x0, 0x0, ...)
        github.com/mrmarble/zmk-viewer/cmd/zmk-viewer/generate/generate.go:84 +0x43a
github.com/mrmarble/zmk-viewer/cmd/zmk-viewer/generate.(*Cmd).Run(0x1)
        github.com/mrmarble/zmk-viewer/cmd/zmk-viewer/generate/generate.go:29 +0x54
reflect.Value.call({0xa38880, 0xc0000f1f28, 0x9faf2e}, {0xa98462, 0x4}, {0xc0000c1a58, 0x0, 0x738848})
        reflect/value.go:556 +0x845
reflect.Value.Call({0xa38880, 0xc0000f1f28, 0xa45dc0}, {0xc0000c1a58, 0x0, 0x0})
        reflect/value.go:339 +0xc5
github.com/alecthomas/kong.callMethod({0xa98250, 0x3}, {0xa7ea80, 0xc0000f1f28, 0x3}, {0xa38880, 0xc0000f1f28, 0x60}, 0x4)
        github.com/alecthomas/kong@v0.5.0/callbacks.go:97 +0x4e7
github.com/alecthomas/kong.(*Context).RunNode(0xc000288f80, 0xc0002e20f0, {0x0, 0x0, 0x0})
        github.com/alecthomas/kong@v0.5.0/context.go:735 +0x40b
github.com/alecthomas/kong.(*Context).Run(0xc000288f80, {0x0, 0x0, 0x0})
        github.com/alecthomas/kong@v0.5.0/context.go:760 +0x115
main.main()
        github.com/mrmarble/zmk-viewer/cmd/zmk-viewer/main.go:65 +0x39f
```

**Comment by MrMarble** [comment]
Fixed in https://github.com/MrMarble/zmk-viewer/releases/tag/v2.0.0
